### ISSUE TITLE
Install via brew

### ISSUE THREAD

**Issue by bradydowling** [Ali-TM-original/SpongbobCli-Rust#1]
I know you probably won't ever make updates to this at this point...but it would still be amazing to have this installable via `brew install spongebob-cli`.

**Comment by Ali-TM-original** [comment]
I would continue working on this don't worry just that busy with exams lately. Anyways I am gonna try pushing it to multiple package managers as soon as possible.

**Comment by Ali-TM-original** [comment]
Well i guess luck and time had something else planned. Won't be doing this :( frustrated so building another tool similar to Spongbob-Cli but better.
